;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	autopair-insert-or-skip-quote
	autopair-newline
	autopair-skip-close-maybe
	c-electric-colon
	c-electric-pound
	c-electric-semi&comma
	c-indent-line-or-region
	find-file
	kill-region
	next-buffer
	previous-buffer
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-slash
	c-electric-star
	comment-dwim
	overwrite-mode
	suspend-frame
	upcase-region
	))
